testBasicMath: CBasicMath.o TestBasicMath.o
	g++ -o testBasicMath CBasicMath.cpp TestBasicMath.cpp -lcppunit
CBasicMath.o:CBasicMath.hpp CBasicMath.cpp
	g++ -c CBasicMath.cpp
TestBasicMath.o:TestBasicMath.cpp
	g++ -c TestBasicMath.cpp
